kind: pipeline
type: kubernetes
name: iot-frontend-ts
steps:
- name: build-frontend
  image: docker:dind
  volumes:
  - name: docker_sock
    path: /var/run
  commands:
  - docker build . -t 10.8.0.14:32000/iot-frontend-ts:latest -t 10.8.0.14:32000/iot-frontend-ts:${DRONE_COMMIT_SHA:0:7}
  - docker push 10.8.0.14:32000/iot-frontend-ts:${DRONE_COMMIT_SHA:0:7}

- name: update manifest repo
  image: alpine/git
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
  commands:
    - mkdir ~/.ssh && chmod 700 ~/.ssh && echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 644 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git clone git@github.com:thommath/Homeserver-CD.git
    - ls
    - cd Homeserver-CD

    - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O yq
    - chmod +x yq
    - ./yq e -i '.spec.template.spec.containers[0].image |= "10.8.0.14:32000/iot-frontend-ts:${DRONE_COMMIT_SHA:0:7}"' 'iot/frontend-deployment.yaml'
    - git add iot/deployment.yaml
    - git commit -m "Bump iot-frontend-ts to ${DRONE_COMMIT_SHA:0:7}"
    - git push

volumes:
  - name: docker_sock
    host:
      path: /var/run

