kind: pipeline
type: kubernetes
name: pixelimage
steps:
- name: build-server
  image: gcr.io/kaniko-project/executor:latest
  environment:
    IMAGE_SERVER:
      from_secret: IMAGE_SERVER
  args:
    - --context=.
    - --destination=${IMAGE_SERVER}/${DRONE_REPO_NAME,,}:${DRONE_COMMIT_SHA:0:7}
    - --insecure  # only if using insecure registry
    - --skip-tls-verify  # only if using self-signed certs

- name: update manifest repo
  image: alpine/git
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
    IMAGE_SERVER:
      from_secret: IMAGE_SERVER
  commands:
    - export IMAGE_TAG="$IMAGE_SERVER/${DRONE_REPO_NAME,,}:${DRONE_COMMIT_SHA:0:7}"
    - export LINE=".spec.template.spec.containers[0].image |= \"$IMAGE_TAG\""

    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - touch ~/.ssh/config
    - touch ~/.ssh/known_hosts
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - chmod -R 400 ~/.ssh

    - git clone git@github.com:thommath/Homeserver-CD.git
    - cd Homeserver-CD

    - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O yq
    - chmod +x yq
    - ./yq e -i "$LINE" 'iot/frontend-deployment.yaml'
    - git add iot/frontend-deployment.yaml
    - git commit -m "Bump ${DRONE_REPO_NAME,,} to ${DRONE_COMMIT_SHA:0:7}"
    - git push

volumes:
  - name: docker_sock
    host:
      path: /var/run